### YamlMime:FAQ
metadata:
  title: الأسئلة المتداولة حول مفاتيح المنتجات
  author: cmcatee-MSFT
  ms.author: cmcatee
  manager: scotv
  ms.reviewer: racheg, armanv
  ms.date: 07/22/2021
  audience: Admin
  ms.topic: faq
  ms.service: o365-administration
  ms.custom: commerce_vl
  ms.localizationpriority: medium
  description: الأسئلة المتداولة حول مفاتيح المنتج
  ms.openlocfilehash: aac4f6aeed6fb8320929d333cdc7b58addfbd221
  ms.sourcegitcommit: 7ac54e1952383d5cd5f084c6a9d247eb747d4904
  ms.translationtype: MT
  ms.contentlocale: ar-SA
  ms.lasthandoff: 06/17/2022
  ms.locfileid: "66139640"
title: الأسئلة المتداولة حول مفاتيح المنتج
summary: ''
sections:
- name: عام
  questions:
  - question: >
      ما هي مفاتيح المنتج؟
    answer: >
      يسمح لك مفتاح المنتج باستخدام منتج برنامج قمت بترخيصه ضمن برنامج ترخيص مجمع محدد. يجب استخدام مفاتيح المنتج المدرجة في مركز مسؤولي Microsoft 365 فقط مع منتجات الترخيص المجمع وهي مخصصة للاستخدام فقط من قبل مؤسستك.


      مفتاح تنشيط الخدمة عبر الإنترنت (OSA) هو مفتاح منتج أحادي الاستخدام يستخدم لتنشيط اشتراكات Microsoft Online Services.


      لمزيد من المعلومات، راجع [الأسئلة المتداولة حول تنشيط الخدمة عبر الإنترنت للبرامج المفتوحة](/licensing/online-service-activation-faq).
  - question: >
      كيف أعمل العثور على مفاتيح المنتج في مركز مسؤولي Microsoft 365؟
    answer: "1. سجل الدخول إلى مركز مسؤولي Microsoft 365. \n2. انتقل إلى **Billing** > **Your products** > **Volume licensing** > **Downloads & keys** > المرور فوق المنتج وحدد **View keys**.\n\nستجد معلومات مفتاح المنتج لكل منتج ونوع الترخيص (مفتاح الترخيص المجمع وخدمة إدارة المفاتيح (KMS) ومفتاح التنشيط المتعدد (MAK) وعدد عمليات تنشيط MAK المستخدمة والمتاحة.\n\nحدد **\"تنزيل كافة مفاتيح المنتج** \" لتنزيل المفاتيح المعروضة لترخيص إلى محرك أقراص محلي.\n"
  - question: >
      كيف أعمل العثور على مفاتيح المنتج SQL Server؟
    answer: >
      يتم تضمين مفتاح ترخيص SQL في معالج تنشيط البرنامج بدلا من عرضه في مركز الإدارة ويتم اكتشافه تلقائيا أثناء التثبيت. لمزيد من المعلومات، راجع [دليل تثبيت SQL Server](/sql/database-engine/install-windows/install-sql-server).


      يمكنك أيضا العثور على المفتاح عن طريق تنزيل ملف ISO SQL من مركز الإدارة >. ملف > DefaultSetup.ini المجلد \x64. تأكد من إجراء نسخ احتياطي لأي إصدار موجود قبل تثبيت إصدارات SQL أو ترقيتها. إذا كنت بحاجة إلى مساعدة في استكشاف المشكلات التقنية وإصلاحها أثناء تثبيت المنتج أو تنشيط الخدمة عبر الإنترنت، فاتصل بقسم الدعم التقني من Microsoft عن طريق إرسال [طلب دعم تقني](https://support.microsoft.com/oas).
  - question: >
      كيف أعمل العثور على مفتاح منتج لشراء الترخيص المجمع؟
    answer: "إذا كانت الاتفاقية تخول الوصول إلى منتج يتطلب مفتاحا، يمكنك العثور على هذه المفاتيح من خلال **الانتقال إلى** >  مفاتيح **تنزيلات الترخيص** >  المجمع **لمنتجاتك** > **&**. \n\nومع ذلك، لا تتطلب بعض المنتجات مفتاح منتج. يتم سرد هذه المعلومات في وصف المنتج في كتالوج التنزيلات والمفاتيح.\n\nلتحديد ما إذا كان منتجك يتطلب مفتاحا، انتقل إلى [تنشيط المنتج ومعلومات المفتاح](https://licensingapps.microsoft.com/product-activation). ضمن \"البحث عن المنتجات\"، اختر منتجا أو ابحث عن اسم المنتج.\n"
  - question: >
      ما هو مفتاح الإعداد؟
    answer: >
      يتم استخدام مفتاح الإعداد لكل مجموعة منتجات/إصدارات لإلغاء تأمين المنتج عن طريق تجاوز التنشيط. يمكنك الحصول على مفتاح الإعداد بإحدى طريقتين:

        - **التنفيذ المادي** بالنسبة إلى المنتجات التي يتم الحصول عليها من خلال التنفيذ الفعلي، تتم طباعة مفتاح الإعداد على كم الوسائط.
        - **إنجاز التنزيل** بالنسبة للمنتجات التي تم الحصول عليها بواسطة التنزيل من مركز الإدارة، يتم عرض مفتاح الإعداد على شاشة التنزيل ويمكن أن يكون مصحوبا بالنص التالي: تتطلب بعض المنتجات المتوفرة للتنزيل مفاتيح الإعداد. لاحظ مفتاح الإعداد كما هو مطلوب أثناء تثبيت المنتج. لمزيد من التفاصيل حول مفاتيح الإعداد، راجع [مفاتيح إعداد عميل KMS](/windows-server/get-started/kmsclientkeys).
  - question: >
      ما الذي يحدد مفاتيح المنتج المقترنة باتفاقياتي؟
    answer: >
      يتم توفير مفاتيح منتج الترخيص المجمع لكل معرف ترخيص مدرج في ["ملخص علاقة Microsoft](/licensing/license-faq)". "ملخص العلاقة" هذا موجود في "مركز خدمة الترخيص المجمع". لمزيد من المعلومات، راجع [ما هو معرف الترخيص](/licensing/license-faq#what-is-a-licensing-id). قد يكون لديك العديد من معرفات الترخيص:

        - يتلقى عملاء اتفاقية Enterprise (EA) و Select Plus مفاتيح المنتج لكل تجمع منتجات (الأنظمة والخوادم والتطبيقات).
        - حدد عملاء الاتفاقية الذين يتلقون مفاتيح المنتجات لكل تجمع منتجات (الأنظمة والخوادم والتطبيقات) استنادا إلى توقعات الشراء الخاصة بهم.
        - يتلقى عملاء الترخيص المفتوح وعملاء Open Value مفاتيح المنتج المعمول بها استنادا إلى مشتريات الترخيص الخاصة بهم.

      لمزيد من المعلومات، راجع [الأسئلة المتداولة حول ملخص الترخيص](/licensing/license-faq).


      > [!NOTE]

      > يحق لجميع العملاء استخدام مفاتيح المنتج لأغراض إعادة التصوير والدرجة النهائية. حدد Plus، اتفاقية Enterprise (EA)، وحدد العملاء لديهم حقوق تقييم محدودة للتدريب والنسخ الاحتياطي. لمزيد من المعلومات، راجع [ملخصات ترخيص المنتج](https://www.microsoft.com/licensing/docs/view/Licensing-Briefs).
- name: تنشيط وحدة التخزين
  questions:
  - question: >
      ما المقصود بتنشيط وحدة التخزين؟
    answer: >
      تنشيط وحدة التخزين هو حل قابل للتكوين يساعد على أتمتة عملية تنشيط المنتج وإدارتها على أجهزة الكمبيوتر التي تعمل Windows أنظمة التشغيل المرخصة ضمن برنامج ترخيص مجمع. كما يستخدم التنشيط المجمع مع برامج أخرى من Microsoft، بما في ذلك مجموعات Office، التي تباع بموجب اتفاقيات الترخيص المجمع والتي تدعم التنشيط المجمع. لمزيد من المعلومات، اطلع على:
        - [أدوات لإدارة تنشيط وحدة التخزين Office](/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office)
        - [تنشيط وحدة التخزين Windows 10](/windows/deployment/volume-activation/volume-activation-windows-10)

      ينطبق تنشيط وحدة التخزين فقط على الأنظمة التي يغطيها برنامج الترخيص المجمع ويتم استخدامه بدقة كأداة للتنشيط. لا يرتبط بفواتير الترخيص أو الفوترة.


      يوفر تنشيط وحدة التخزين طريقتين لإكمال عمليات تنشيط وحدة التخزين. يمكن استخدام أي من النوعين الرئيسيين أو كليهما من قبل العملاء لتنشيط الأنظمة في مؤسستهم:
        - تسمح خدمة إدارة المفاتيح (KMS) للمؤسسات بتنشيط الأنظمة داخل شبكتها الخاصة.
        - يقوم مفتاح التنشيط المتعدد (MAK) بتنشيط الأنظمة مرة واحدة، باستخدام خدمات التنشيط المستضافة من Microsoft.
  - question: >
      ما هي خدمة إدارة المفاتيح (KMS)؟
    answer: >
      KMS هي خدمة تنشيط تسمح للمؤسسات بتنشيط الأنظمة داخل شبكتها الخاصة عن طريق القضاء على الحاجة إلى أجهزة الكمبيوتر الفردية للاتصال ب Microsoft لتنشيط المنتج. لا يتطلب نظاما مخصصا ويمكن استضافته على نظام يوفر خدمات أخرى.


      يتطلب KMS حدا أدنى من أجهزة الكمبيوتر الفعلية أو الظاهرية في بيئة الشبكة. يتم تعيين هذه الحدود الدنيا، التي تسمى عتبات التنشيط، بحيث يمكن تلبيتها بسهولة من قبل عملاء Enterprise.

        - حدود التنشيط Windows
          - يجب أن يكون لدى مؤسستك 5 أجهزة كمبيوتر على الأقل لتنشيط الخوادم التي تعمل Windows Server.
          - يجب أن يكون لدى مؤسستك 25 جهاز كمبيوتر على الأقل لتنشيط أنظمة العملاء التي تعمل Windows.
        - حدود التنشيط Office
          - يجب أن يكون لدى مؤسستك ما لا يقل عن 5 أجهزة كمبيوتر تقوم بتشغيل إصدار من Office لتنشيط منتجات Office المثبتة باستخدام KMS.

      لمزيد من المعلومات حول حدود التنشيط، راجع [دليل تخطيط تنشيط وحدة التخزين](/windows/deployment/volume-activation/volume-activation-windows-10).
  - question: >
      ما هو مفتاح مضيف KMS؟
    answer: >
      يتم استخدام مفتاح KMS لتنشيط الكمبيوتر المضيف KMS مع خادم تنشيط Microsoft ويمكنه تنشيط ما يصل إلى 6 كم من مضيفي KMS مع 10 عمليات تنشيط لكل مضيف. يمكن لكل مضيف KMS تنشيط عدد غير محدود من أجهزة الكمبيوتر.
  - question: >
      لماذا لا يتم عرض مفتاح KMS على مركز مسؤولي Microsoft 365 لعملاء الترخيص المفتوح؟
    answer: "لم تعد مفاتيح KMS معينة مسبقا للاتفاقيات المفتوحة لأن استخدام مفتاح التنشيط المتعدد (MAK) هو الأسلوب المفضل للتنشيط.\n\nيمكن تعيين مفاتيح KSM، على سبيل الاستثناء، للعملاء المفتوحين الذين يستوفون الحد الأدنى من عتبة تنشيط KMS لخادم Windows ونظام التشغيل Office. لطلب استثناء، أرسل طلب نموذج ويب إلى دعم Microsoft.\n\nلطلب استثناء، يجب أن يكون لديك أذونات مسؤول VLSC أو مسؤول المفتاح أو عارض المفاتيح وتوفير المعلومات التالية:\n  \n  - رقم الاتفاقية/التسجيل أو معرف الترخيص والتخويل.\n  - اسم المنتج (بما في ذلك الإصدار والنسخة).\n  - آخر 5 أحرف من مفتاح المنتج.\n  - عدد عمليات تنشيط المضيف المطلوبة.\n  - مبررات العمل أو سبب النشر.\n"
  - question: >
      ماذا لو احتجت إلى مضيفي KMS إضافيين؟
    answer: "إذا كنت تحتاج إلى عمليات تنشيط KMS إضافية لتنشيط أكثر من 6 كم من مضيفي KMS، أرسل طلب نموذج ويب مركز مسؤولي Microsoft 365 الدعم. \n\nلطلب استثناء، يجب أن يكون لديك أذونات مسؤول VLSC أو مسؤول المفتاح أو عارض المفاتيح وتوفير المعلومات التالية:\n  \n  - رقم الاتفاقية/التسجيل أو معرف الترخيص والتخويل.\n  - اسم المنتج (بما في ذلك الإصدار والنسخة).\n  - آخر 5 أحرف من مفتاح المنتج.\n  - عدد عمليات تنشيط المضيف المطلوبة.\n  - مبررات العمل أو سبب النشر.\n"
  - question: >
      ما هو مفتاح التنشيط المتعدد (MAK)؟
    answer: >
      يقوم مفتاح التنشيط المتعدد (MAK) بتنشيط الأنظمة مرة واحدة، باستخدام خدمات التنشيط المستضافة من Microsoft التي تتطلب الاتصال بخادم تنشيط Microsoft. بمجرد تنشيط أجهزة الكمبيوتر، لا يلزم إجراء مزيد من الاتصالات مع Microsoft.


      **الهامه** يستند عدد عمليات تنشيط MAK المسموح بها إلى اتفاقية الترخيص المجمع.
  - question: >
      لماذا لا يتطابق عدد عمليات تنشيط MAK المتوفرة مع عدد التراخيص التي اشتريناها؟
    answer: >
      نوصي العملاء باستخدام KMS لتنشيط مفاتيح التنشيط المتعددة (MAK). KMS هو أسلوب التنشيط المفضل لعمليات النشر واسعة النطاق. تحدد العديد من العوامل عدد عمليات التنشيط المقترنة بكل MAK، بما في ذلك التراخيص التي تم شراؤها ومستوى تسعير شراء العميل وبرنامج الترخيص المجمع الخاص بهم.


      لن يتطابق عدد عمليات التنشيط المتوفرة لمنتج دائما مع عدد التراخيص التي تم شراؤها. عادة ما تتلقى المزيد من عمليات التنشيط في حالة الحاجة إلى إعادة تثبيت بعض منتجاتك وتنشيطها. تحقق من قسم "ملخص الترخيص" في الاتفاقية لعرض عدد التراخيص.
  - question: >
      كيف أعمل طلب زيادة إلى حدود تنشيط MAK؟
    answer: "يمكن طلب الزيادات في كمية تنشيط MAK عبر نموذج ويب ويتم منحها حسب الاستثناء. بالنسبة إلى كندا والولايات المتحدة، أرسل [طلبات دعم الترخيص المجمع](https://support.microsoft.com/supportrequestform/2afa6f15-b710-db46-909a-8346017c802f). بالنسبة إلى جميع البلدان الأخرى، أرسل [نموذج ويب للدعم](/licensing/contact-us). \n\nلطلب حد تنشيط MAK، يجب أن يكون لديك أذونات مسؤول VLSC أو مسؤول المفتاح أو عارض المفاتيح وتوفير المعلومات التالية:\n\n  - رقم الاتفاقية/التسجيل أو معرف الترخيص والتخويل.\n  - اسم المنتج (بما في ذلك الإصدار والنسخة).\n  - آخر 5 أحرف من مفتاح المنتج.\n  - عدد عمليات تنشيط المضيف المطلوبة.\n  - مبررات العمل أو سبب النشر.\n"
  - question: >
      كيف أعمل تنشيط التراخيص باستخدام مفتاح تنشيط متعدد (MAK)؟
    answer: >
      يمكنك تنشيط التراخيص بإحدى الطريقتين باستخدام MAK:

        - يتصل كل كمبيوتر بشكل فردي ب Microsoft من خلال استخدام الويب أو الهاتف لإكمال التنشيط.
        - يتم إجراء طلب تنشيط مركزي واحد لتنشيط وكيل MAK نيابة عن أجهزة كمبيوتر متعددة ذات اتصال واحد ب Microsoft عبر الإنترنت أو عبر الهاتف. يستخدم هذا الأسلوب أداة إدارة تنشيط وحدة التخزين (VAMT)، وهي جزء من Windows أداة التثبيت التلقائي (WAIK). تمكن VAMT محترفي تكنولوجيا المعلومات من أتمتة عملية تنشيط وحدة التخزين وإدارتها مركزيا باستخدام MAK وتتضمن التحقق من عدد عمليات التنشيط على MAK.
  - question: >
      ما هي أداة إدارة تنشيط وحدة التخزين (VAMT)؟
    answer: >
      أداة إدارة تنشيط وحدة التخزين (VAMT) هي أداة تسمح لمسؤولي الشبكة ومحتربي تكنولوجيا المعلومات الآخرين بأتمتة عملية تنشيط وحدة التخزين والبيع بالتجزئة وإدارتها مركزيا Windows Microsoft Office وتحديد منتجات Microsoft الأخرى. يمكن ل VAMT إدارة تنشيط وحدة التخزين باستخدام مفاتيح التنشيط المتعددة (MAKs) أو Windows Key Management Service (KMS). VAMT هي أداة إضافية قياسية لوحدة تحكم إدارة Microsoft (MMC) تتطلب وحدة تحكم إدارة Microsoft (MMC) 3.0.


      للحصول على معلومات حول VAMT، راجع:

        - [مرجع تقني لأداة إدارة تنشيط وحدة التخزين (VAMT)](/windows/deployment/volume-activation/volume-activation-management-tool)
        - [إدارة التنشيط باستخدام أداة إدارة تنشيط وحدة التخزين (VAMT)](/previous-versions/tn-archive/ff686876(v=technet.10))
        - تنزيل [أداة إدارة تنشيط وحدة التخزين (VAMT)](https://www.microsoft.com/download/details.aspx?id=11936)
  - question: >
      ما الذي يجب معرفته حول استخدام Windows Server كمضيف KMS لتنشيط عملاء Windows؟
    answer: "إذا قمت بنشر Windows باستخدام Key Management Service (KMS) كطريقة تنشيط، لاحظ ما يلي:\n  \n  - Windows Server غير معتمد كمضيف KMS لتنشيط Windows.\n  - مطلوب مفتاح Windows Server KMS للحصول على تصحيح للسماح بتنشيط أجهزة العميل Windows. للحصول على أحدث تصحيح، راجع [تكوين كمبيوتر مضيف KMS لتنشيط الإصدارات المرخصة المجمعة من Office](/deployoffice/vlactivation/configure-a-kms-host-computer-for-office). \n\nإذا كنت تستخدم Windows Server كمضيف KMS، يمكنك:\n  \n  - ترقية الجهاز المضيف KMS إلى Windows Server.\n  - خفض إصدار الجهاز إلى Windows Server 2003.\n  - تشغيل مضيف KMS على جهاز إصدار مجمع Windows.\n  - تشغيل جهاز ظاهري Windows Server.\n"
  - question: >
      ما الذي يجب معرفته حول تنشيط وحدة التخزين Office Project Visio؟
    answer: >
      ترتبط تغييرات تنشيط وحدة التخزين التالية Office Project Visio:
        - Office كمس Host ينشط أي مجموعة Office أو تطبيق.
        - يجب تثبيت مفتاح OFFICE KMS واحد فقط واستخدامه للتنشيط.

      إذا قمت بنشر Office باستخدام Key Management Service (KMS) كطريقة تنشيط، لاحظ ما يلي:
        - لا يمكنك تنشيط Office باستخدام KMS إذا كنت تستخدم Windows Server كمضيف KMS.
        - لا يتوفر تصحيح للسماح بتنشيط عملاء Office.

      إذا كنت تستخدم Windows Server 2008 كمضيف KMS، يمكنك:
        - ترقية الجهاز المضيف KMS إلى Windows Server.
        - قم بتصغير الجهاز إلى إصدار أقدم من Windows Server.
        - تشغيل مضيف KMS على كمبيوتر Windows.
        - تشغيل جهاز ظاهري Windows Server على إصدار أحدث من Windows Server.
  - question: >
      كيف أعمل تنشيط وحدة طرفية لـ Windows Server وخدمة سطح المكتب البعيد (RDS)؟
    answer: >
      بعد تنزيل وسائط الخادم من VLSC، يمكنك تنشيطها باستخدام معالج تنشيط المنتج. لا تحتاج إلى تحديد موقع مفتاح ترخيص مجمع أو مفتاح إعداد المنتج في VLSC. يتطلب إكمال جميع خطوات معالج التنشيط من الخادم الاتصال ب Microsoft Clearing House عبر الإنترنت للتحقق من صحة البيانات. بدلا من ذلك، بالنسبة إلى الخوادم غير المتصلة، يقدم معالج التنشيط تنشيط الهاتف أو الويب.


      للبدء، قم بتعيين دور ترخيص سطح المكتب البعيد للخادم( **Start** > **Administrative Tools** > **Server Manager**) ثم قم بتنشيط خدمة RDS من Remote Desktop License Manager. حدد **Start** > **Administrative Tools** > **Remote Desktop Services**، ثم حدد **Remote Desktop/Terminal License Manager**.


      أثناء التنشيط، يطلب منك تحديد برنامج الترخيص ورقم الاتفاقية. لعملاء الترخيص المفتوح، أدخل رقم التخويل الخاص بك. بالنسبة إلى MPSA، أدخل رقم حساب الشراء (وليس رقم اتفاقية MPSA). إذا لم تكن متأكدا من نوع البرنامج لمعرف الترخيص المستخدم لشراء تراخيص CAL، فانتقل إلى **"ملخص علاقة VLSC** " وارجع إلى العمود **"البرنامج الأصل** ".


      للحصول على معلومات حول ترخيص Terminal Server، راجع [ترخيص Terminal Server](/troubleshoot/windows-server/remote/terminal-server-licensing). للحصول على معلومات حول كيفية تثبيت دور ترخيص سطح المكتب البعيد وتنشيط خادم الترخيص، راجع [تنشيط خادم ترخيص خدمات سطح المكتب البعيد](/windows-server/remote/remote-desktop-services/rds-activate-license-server)  [وتعذر الاتصال ب RDS بسبب عدم توفر خوادم ترخيص RD](/troubleshoot/windows-server/remote/cannot-connect-rds-no-license-server).
  - question: >
      هل يمكن للمؤسسات داخل بنية الملكية نفسها استخدام نفس المفتاح لتوزيع منتج؟
    answer: >
      إن توافق الترخيص وإدارة الأصول مستقلان عن التنشيط الرئيسي. لا يتعين على العملاء استخدام المفاتيح المتوفرة بموجب معرف ترخيص معين (اتفاقية أو تسجيل أو شركة تابعة أو ترخيص). إذا كانت المؤسسة الأصل لديها اتفاقية فردية، فيمكنها استخدام المفتاح نفسه لنشر منتج عبر المؤسسات الأصل والتابعة. تسمح هذه المرونة للعملاء بإدارة صورة التوزيع الخاصة بهم مركزيا باستخدام إما المفاتيح الخاصة بالاتفاقيات/التراخيص أو مجموعة واحدة من المفاتيح للجميع.
  - question: >
      هل يمكنني استخدام مفاتيح الترخيص المجمع لممارسة حقوق إعادة التصوير الخاصة بي؟
    answer: >
      نعم. يتم منح حقوق إعادة التصوير لجميع عملاء الترخيص المجمع من Microsoft. بموجب هذه الحقوق، يمكن للعملاء إعادة تصوير النسخ المرخصة من الشركة المصنعة للمعدات الأصلية (OEM) أو Full Packaged Product (FPP) باستخدام الوسائط المقدمة بموجب موافقتهم إذا كانت النسخ التي تم إنشاؤها من وسائط الترخيص المجمع متطابقة مع المنتج المرخص الأصلي. بصفتك عميل ترخيص مجمع، يمكنك العثور على مفاتيح الترخيص المجمع في صفحة مفتاح المنتج أو طلب المفاتيح من خلال [مركز تنشيط Microsoft](https://licensingapps.microsoft.com/product-activation).


      > [!NOTE]

      > إذا كنت عميل ترخيص مفتوح، يجب شراء وحدة واحدة على الأقل من المنتج الذي تريد إعادة صورته للحصول على حق الوصول إلى وسائط المنتج وتلقي مفتاح المنتج.


      لمزيد من المعلومات حول حقوق إعادة التصوير، راجع [ملخصات ترخيص المنتج](https://www.microsoft.com/licensing/docs/view/Licensing-Briefs).
  - question: >
      كيف أعمل تنزيل مفاتيحي إلى ملف محلي؟
    answer: "يوفر مركز مسؤولي Microsoft 365 خيارا لتنزيل مفاتيح المنتج إلى ملف محلي لاستخدامها لاحقا. عند تنزيل مفاتيح المنتج من صفحة التنزيلات والمفاتيح، يحتوي الملف على كافة مفاتيح الترخيص المجمع المقترنة بالاتفاقيات في ملف تعريف مركز الإدارة. ومع ذلك، إذا قمت بتنزيل المفاتيح من طريقة عرض \"معرف الترخيص\" في الصفحة \"ملخص العلاقة\"، فسيحتوي الملف على المفاتيح المقترنة بمعرف الترخيص الذي تعرضه فقط.\n\nملف مفتاح المنتج القابل للتنزيل بتنسيق محدد بعلامات جدولة ويمكن فتحه Excel أو محرر نص لفرز المفاتيح وعرضها. هذه هي الأعمدة المضمنة في الملف: **معرف الترخيص** **والبرنامج الأصل** **والمؤسسة** **والمنتج** **ومفتاح المنتج** **والنوع** **والتنشيط MAK المستخدم/المتاح والتراخيص وحالة OSA**. \n\nلفتح ملف تم تنزيله في Excel، أكمل الخطوات التالية:\n  1. افتح Microsoft Excel.\n  2. حدد \"**فتح** **ملف** > \"، ثم حدد ملف CSV الذي تم تنزيله.\n  3. حدد **محدد** (الافتراضي)، ثم حدد **\"مفصول بعلامة جدولة** \" (لمنع عرض كافة البيانات في عمود واحد).\n  4. حدد **إنهاء**. \n\nيتم فتح ملف .CSV في Excel ويتم عرض البيانات في أعمدة منفصلة.\n"
- name: الدعم
  questions:
  - question: >
      هل كيف أعمل الاتصال بالدعم؟
    answer: >
      مركز مسؤولي Microsoft 365 يمكن للعملاء الاتصال بالدعم عبر الهاتف أو نموذج ويب. تستجيب Microsoft لإرسالات نماذج الويب في غضون 24 ساعة. للاتصال بالدعم، راجع [الاتصال بنا](/licensing/contact-us).
additionalContent: "\n## <a name=\"additional-resources\"></a>موارد إضافية\n\n- [الأسئلة المتداولة حول التنزيلات](downloads-faq.yml)\n\n- [الأسئلة المتداولة حول تنشيط الخدمة عبر الإنترنت للبرامج المفتوحة](online-service-activation-faq.yml)"
